--- #YAML:1.0
name:               Config-General
version:            2.56
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Glob:           0
    File::Spec::Functions:  0
    FileHandle:           0
    IO::File:             0
resources:
    repository:  http://dev.catalyst.perl.org/repos/Config-General/trunk/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
